
services:
  mongodb:
    container_name: mongodb
    image: mongo:8.0.3
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ${MONGO_VOLUME_PATH}:/data/db
#  web: TODO: later
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    depends_on:
#      - mongodb
#    container_name: cam-classificator
#    restart: always
#    ports:
#      - "5000:5000"

