services:
  mongodb:
    container_name: mongodb
    image: mongo:8.0.3
    restart: always
    ports:
      - '27017:27017'
    networks:
      - cam_classificator_network
    volumes:
      - ../data:/data/db
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    container_name: cam-classificator
    restart: always
    ports:
      - "8080:8080"
    environment:
      DEBUG: false
      MONGO_URL: mongodb:27017
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8080
      PHOTO_DICT: /photos

      SECRET_KEY: 123
      API_KEY: 456
    networks:
      - cam_classificator_network
    volumes:
      - ./:/app
      - ../photos:/photos


networks:
  cam_classificator_network:
 
